### ISSUE TITLE
Moved almost all logic to child components 

### ISSUE THREAD

**Issue by patrickcandlin** [LimitToInfinity/growth_front#1]
Hello sir! 

This is what I was talking about on Thursday. Take a look and let me know if you any questions. The main benefit of rendering child components this way is the each component becomes much more independent.

Please see the my pull request

**Comment by LimitToInfinity** [comment]
Hi Good Sir!

This is fantastic. I like that you're only rendering the components when their condition becomes true. I'm thinking some of the If/Else statements could be ternaries. Either way looks much better and I like the separation of concerns.

Thanks for working on this!
